/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findAll"];
        put?: never;
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AssetsController_findAll"];
        put?: never;
        post: operations["AssetsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a broker-specific asset alias
         * @description Maps a Cathay broker display name to an existing catalog Asset. Creating the same normalized (alias, broker) pair for the same Asset is idempotent. If the pair already maps to another Asset, returns ASSET_ALIAS_CONFLICT without overwriting.
         */
        post: operations["AssetsController_createAlias"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/symbol/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AssetsController_findBySymbol"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AssetsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["AssetsController_remove"];
        options?: never;
        head?: never;
        patch: operations["AssetsController_update"];
        trace?: never;
    };
    "/fx/rates/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FxRateController_getTodayRate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MarketPriceController_refreshPrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/sync/taiwan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MarketPriceController_syncTaiwanPrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/sync/us": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MarketPriceController_syncUsPrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corp-actions/sync/splits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CorpActionController_syncSplits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corp-actions/{id}/cash-in-lieu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record confirmed broker cash in lieu of fractional shares */
        post: operations["CashInLieuController_record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gl/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GlController_getAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gl/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GlController_getEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gl/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GlController_transfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gl/expense": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GlController_expense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gl/income": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GlController_income"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AccountsController_findAll"];
        put?: never;
        post: operations["AccountsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AccountsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["AccountsController_remove"];
        options?: never;
        head?: never;
        patch: operations["AccountsController_update"];
        trace?: never;
    };
    "/onboarding/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OnboardingController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TransactionsController_findAll"];
        put?: never;
        post: operations["TransactionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deprecated: use POST /transactions/import/preview then /transactions/import/commit
         * @deprecated
         * @description Prefer preview + commit. This endpoint follows the same commit-time plan (ready-only chronological writes).
         */
        post: operations["TransactionsController_importTransactions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview broker CSV import
         * @description Evaluates rows without writing. Applies chronological sell-readiness planning and returns typed row statuses. canCommit is true when there is at least one ready row and no commit-blocking error (file-internal duplicate), or when the upload is all-skipped. Sell codes SELL_HISTORY_REQUIRED, SELL_INSUFFICIENT_LOTS, and SELL_SAME_DAY_ORDER_AMBIGUOUS are row-local and do not block other ready rows.
         */
        post: operations["TransactionsController_previewImportTransactions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/import/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit broker CSV import
         * @description Re-evaluates the same plan as preview, then creates only ready rows in chronological write order. Error and skipped rows are not written. Unexpected create failures still return IMPORT_COMMIT_FAILED.
         */
        post: operations["TransactionsController_commitImportTransactions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TransactionsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["TransactionsController_remove"];
        options?: never;
        head?: never;
        patch: operations["TransactionsController_update"];
        trace?: never;
    };
    "/transactions/{id}/hard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["TransactionsController_hardDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GL summary
         * @description General-ledger totals for the signed-in user. The product homepage uses /portfolio, not this route.
         */
        get: operations["DashboardController_getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GL activity
         * @description Recent general-ledger activity. Not the holding activity line on the portfolio homepage.
         */
        get: operations["DashboardController_getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PortfolioController_getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PortfolioController_getHoldings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/rebalance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PortfolioController_getRebalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PortfolioController_getTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/holdings/{assetId}/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PortfolioController_getHoldingTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example 400 */
            statusCode: number;
            /** @example Bad Request */
            error: string;
            /** @example Entry not balanced: debit=..., credit=... */
            message: string;
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example correct horse battery staple */
            password: string;
        };
        AuthUserDto: {
            id: string;
            email: string;
            /** @enum {string} */
            role: "admin" | "user";
        };
        CreateUserDto: {
            /** @example user@example.com */
            email: string;
            /** @example user123 */
            password: string;
        };
        UserResponseDto: {
            id: string;
            email: string;
            /** @enum {string} */
            role: "admin" | "user";
            /** Format: date-time */
            createdAt: string;
        };
        CreateAndUpdateAssetDto: {
            /**
             * @description 資產代號
             * @example AAPL
             */
            symbol: string;
            /**
             * @description 資產名稱
             * @example Apple Inc.
             */
            name: string;
            /**
             * @description 資產類型
             * @example equity
             * @enum {string}
             */
            type: "equity" | "etf" | "crypto" | "cash";
            /**
             * @description 基礎貨幣
             * @example USD
             * @enum {string}
             */
            baseCurrency: "TWD" | "USD" | "JPY" | "EUR";
            /**
             * @description 資產本質分類；若省略，後端只會在可明確推論時自動補上
             * @example equity
             * @enum {string}
             */
            assetClass?: "equity" | "bond" | "cash" | "crypto" | "precious_metal";
        };
        AssetResponseDto: {
            /**
             * @description 資產代號
             * @example AAPL
             */
            symbol: string;
            /**
             * @description 資產名稱
             * @example Apple Inc.
             */
            name: string;
            /**
             * @description 資產類型
             * @example equity
             * @enum {string}
             */
            type: "equity" | "etf" | "crypto" | "cash";
            /**
             * @description 資產本質分類
             * @example equity
             * @enum {string}
             */
            assetClass: "equity" | "bond" | "cash" | "crypto" | "precious_metal";
            /**
             * @description 基礎貨幣
             * @example USD
             * @enum {string}
             */
            baseCurrency: "TWD" | "USD" | "JPY" | "EUR";
            /** @example e8e1d0a6-... */
            id: string;
        };
        CreateAssetAliasDto: {
            /**
             * @description Raw broker display name to map to an existing Asset
             * @example 國泰台灣領袖50
             */
            alias: string;
            /**
             * @description Broker scope for the alias. Only Cathay is accepted in this flow.
             * @example cathay
             * @enum {string}
             */
            broker: "cathay";
        };
        AssetAliasMappedAssetDto: {
            /** @example e8e1d0a6-... */
            id: string;
            /** @example 00900 */
            symbol: string;
            /** @example 國泰台灣領袖50 */
            name: string;
        };
        AssetAliasResponseDto: {
            /** @example a1b2c3d4-... */
            id: string;
            /** @example e8e1d0a6-... */
            assetId: string;
            /** @example 國泰台灣領袖50 */
            alias: string;
            /** @example cathay */
            broker: string;
            asset: components["schemas"]["AssetAliasMappedAssetDto"];
        };
        AssetAliasConflictResponseDto: {
            /** @example ASSET_ALIAS_CONFLICT */
            code: string;
            /** @example Asset alias already maps to another asset */
            message: string;
            existingAsset: components["schemas"]["AssetAliasMappedAssetDto"];
        };
        AssetListResponseDto: {
            items: components["schemas"]["AssetResponseDto"][];
            /** @example 42 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 10 */
            take: number;
        };
        FxRateResponseDto: {
            /** @example TWD */
            base: string;
            /** @example USD */
            quote: string;
            /** @example 0.03125 */
            rate: number;
            /** @example 2026-04-14 */
            date: string;
            /** @example db */
            provider: string;
        };
        RefreshPricesMarketResultDto: {
            /** @enum {string} */
            market: "tw" | "us";
            /** @enum {string} */
            status: "success" | "failed";
            /** @example 2026-07-20 */
            startDate?: string;
            /** @example 2026-08-02 */
            endDate?: string;
            assetsProcessed?: number;
            rowsUpserted?: number;
            /** @example PRICE_REFRESH_FAILED */
            errorCode?: string;
            /** @example US price refresh failed */
            message?: string;
        };
        RefreshPricesResponseDto: {
            /** @enum {string} */
            status: "success" | "partial_success" | "failed";
            /** @description Fixed order: tw, then us. */
            markets: components["schemas"]["RefreshPricesMarketResultDto"][];
        };
        SyncTaiwanPricesDto: {
            /**
             * @description daily = recent window; backfill = first buy → today for incomplete assets
             * @default daily
             * @enum {string}
             */
            mode: "daily" | "backfill";
            /** @example 2026-05-27 */
            startDate?: string;
            /** @example 2026-06-03 */
            endDate?: string;
            /**
             * @description Backfill only: max assets per run (FinMind rate limit)
             * @default 10
             */
            maxAssetsPerRun: number;
            /** @description Limit sync to specific assets (UUIDs) */
            assetIds?: string[];
        };
        SyncTaiwanPricesPerAssetDto: {
            assetId: string;
            symbol: string;
            rows: number;
            skipped?: boolean;
            reason?: string;
        };
        SyncTaiwanPricesResponseDto: {
            /** @example tw */
            market: string;
            /** @enum {string} */
            mode: "daily" | "backfill";
            startDate: string;
            endDate: string;
            assetsRequested: number;
            assetsProcessed: number;
            assetsSkipped: number;
            rowsUpserted: number;
            perAsset: components["schemas"]["SyncTaiwanPricesPerAssetDto"][];
        };
        SyncUsPricesDto: {
            /**
             * @description daily = recent window; backfill = first buy → today for incomplete assets
             * @default daily
             * @enum {string}
             */
            mode: "daily" | "backfill";
            /** @example 2026-05-27 */
            startDate?: string;
            /** @example 2026-06-03 */
            endDate?: string;
            /**
             * @description Backfill only: max assets per run (FinMind rate limit)
             * @default 10
             */
            maxAssetsPerRun: number;
            /** @description Limit sync to specific assets (UUIDs) */
            assetIds?: string[];
        };
        SyncUsPricesPerAssetDto: {
            assetId: string;
            symbol: string;
            rows: number;
            skipped?: boolean;
            reason?: string;
        };
        SyncUsPricesResponseDto: {
            /** @example us */
            market: string;
            /** @enum {string} */
            mode: "daily" | "backfill";
            startDate: string;
            endDate: string;
            assetsRequested: number;
            assetsProcessed: number;
            assetsSkipped: number;
            rowsUpserted: number;
            perAsset: components["schemas"]["SyncUsPricesPerAssetDto"][];
        };
        SyncSplitsDto: {
            /**
             * @default all
             * @enum {string}
             */
            market: "tw" | "us" | "all";
            /** @example 2020-01-01 */
            startDate?: string;
            /** @example 2026-06-05 */
            endDate?: string;
            assetIds?: string[];
        };
        SyncSplitsResponseDto: {
            /** @enum {string} */
            market: "tw" | "us" | "all";
            assetsProcessed: number;
            eventsUpserted: number;
            scopesReplayed: number;
            /** @description True when split events were stored but affected-scope replay has not run yet. */
            replayPending: boolean;
        };
        CashInLieuDto: {
            accountId: string;
            /**
             * @description Actual net cash received, as a decimal string
             * @example 12.34
             */
            amount: string;
            /**
             * @description Fractional shares disposed per broker statement
             * @example 0.5
             */
            quantity: string;
            /** @enum {string} */
            currency: "TWD" | "USD" | "JPY" | "EUR";
            /** @example 2025-06-20T00:00:00Z */
            paidAt: string;
            /** @description Broker statement/payment reference */
            reference: string;
        };
        GetAccountDto: {
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            id: string;
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            userId: string;
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            name: string;
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            type: string;
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            currency: string;
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            linkedAccountId: string;
        };
        GlLineDto: {
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            id: string;
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            glAccountId: string;
            /** @example Expense: Food */
            glAccountName: string;
            /**
             * @example debit
             * @enum {string}
             */
            side: "debit" | "credit";
            /** @example 320 */
            amount: number;
            /** @example TWD */
            currency: string;
        };
        GlEntryDto: {
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            id: string;
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            userId: string;
            /** @example 2025-01-15T10:00:00Z */
            date: string;
            /** @example Transfer from account to account */
            memo: string;
            /** @example manual:transfer */
            source: string;
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            refTxId: string;
            lines: components["schemas"]["GlLineDto"][];
        };
        PostTransferCommand: {
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            fromGlAccountId: string;
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            toGlAccountId: string;
            /** @example 1000 */
            amount: number;
            /**
             * @example TWD
             * @enum {string}
             */
            currency: "TWD" | "USD" | "JPY" | "EUR";
            /** @example 2025-01-01T00:00:00.000Z */
            date?: string;
            /** @example Transfer from account to account */
            memo?: string;
            /** @example manual:transfer */
            source?: string;
        };
        PostExpenseCommand: {
            /** @example GL_ACC_ID_CASH_OR_BANK */
            payFromGlAccountId: string;
            /** @example GL_ACC_ID_EXPENSE */
            expenseGlAccountId: string;
            /** @example 320 */
            amount: number;
            /**
             * @example TWD
             * @enum {string}
             */
            currency: "TWD" | "USD" | "JPY" | "EUR";
            /** @example 2025-11-04T12:00:00.000Z */
            date?: string;
            /** @example Lunch */
            memo?: string;
            /** @example manual:expense */
            source?: string;
        };
        PostIncomeCommand: {
            /** @example GL_ACC_ID_CASH_OR_BANK */
            receiveToGlAccountId: string;
            /** @example GL_ACC_ID_INCOME */
            incomeGlAccountId: string;
            /** @example 1500 */
            amount: number;
            /**
             * @example TWD
             * @enum {string}
             */
            currency: "TWD" | "USD" | "JPY" | "EUR";
            /** @example 2025-11-04T09:30:00.000Z */
            date?: string;
            /** @example Salary (partial) */
            memo?: string;
            /** @example manual:income */
            source?: string;
        };
        CreateAndUpdateAccountDto: {
            /**
             * @description 帳戶名稱
             * @example My Broker Account
             */
            name: string;
            /**
             * @description 帳戶類型
             * @example broker
             * @enum {string}
             */
            type: "broker" | "bank" | "cash";
            /**
             * @description 幣別
             * @example TWD
             * @enum {string}
             */
            currency: "TWD" | "USD" | "JPY" | "EUR";
            /**
             * @description 券商識別碼，只有 broker account 需要
             * @example cathay
             */
            broker?: string;
        };
        AccountResponseDto: {
            /**
             * @description 帳戶名稱
             * @example My Broker Account
             */
            name: string;
            /**
             * @description 帳戶類型
             * @example broker
             * @enum {string}
             */
            type: "broker" | "bank" | "cash";
            /**
             * @description 幣別
             * @example TWD
             * @enum {string}
             */
            currency: "TWD" | "USD" | "JPY" | "EUR";
            /**
             * @description 券商識別碼，只有 broker account 需要
             * @example cathay
             */
            broker?: string;
            /** @example e8e1d0a6-... */
            id: string;
            /** @example c2610e4e-1cca-401e-afa7-1ebf541d0000 */
            userId: string;
            /**
             * Format: date-time
             * @example 2025-10-08T05:00:00.000Z
             */
            createdAt: string;
        };
        OnboardingStarterAccountDto: {
            /** @example My Broker Account */
            name: string;
            /**
             * @example broker
             * @enum {string}
             */
            type: "broker" | "bank" | "cash";
            /**
             * @default TWD
             * @example TWD
             * @enum {string}
             */
            currency: "TWD";
            /**
             * @description 券商識別碼，只有 broker account 需要
             * @example cathay
             */
            broker?: string;
        };
        OnboardingSignupDto: {
            /** @example user@example.com */
            email: string;
            /** @example user123 */
            password: string;
            starterAccount: components["schemas"]["OnboardingStarterAccountDto"];
        };
        OnboardingSignupResponseDto: {
            user: components["schemas"]["UserResponseDto"];
            starterAccount: components["schemas"]["AccountResponseDto"];
        };
        CreateTransactionDto: {
            /**
             * @description 帳戶ID
             * @example c2610e4e-1cca-401e-afa7-1ebf541d0000
             */
            accountId: string;
            /**
             * @description 資產ID
             * @example e8e1d0a6-1234-5678-9abc-def012345678
             */
            assetId?: string;
            /**
             * @description 交易類型
             * @example buy
             * @enum {string}
             */
            type: "buy" | "sell" | "deposit" | "withdraw" | "dividend" | "fee";
            /**
             * @description 交易金額
             * @example 1000.5
             */
            amount: number;
            /**
             * @description 交易數量
             * @example 10
             */
            quantity?: number;
            /**
             * @description 交易價格
             * @example 100.05
             */
            price?: number;
            /**
             * @description 手續費
             * @example 5
             */
            fee?: number;
            /**
             * @description 交易稅額
             * @example 3
             */
            tax?: number;
            /**
             * @description 券商委託書號
             * @example k0C1i
             */
            brokerOrderNo?: string;
            /**
             * @description 交易時間
             * @example 2025-01-20T10:30:00.000Z
             */
            tradeTime?: string;
            /**
             * @description 備註
             * @example Buy AAPL shares
             */
            note?: string;
        };
        TransactionAccountSummaryDto: {
            id: string;
            name: string;
            currency: string;
            userId: string;
        };
        TransactionAssetSummaryDto: {
            id: string;
            symbol: string;
            name: string;
            baseCurrency: string;
        };
        TransactionResponseDto: {
            id: string;
            accountId: string;
            assetId?: string | null;
            /** @enum {string} */
            type: "buy" | "sell" | "deposit" | "withdraw" | "dividend" | "fee";
            /**
             * @description 十進位字串，不是 number
             * @example 1000.50
             */
            amount: string;
            /** @example 10 */
            quantity?: string | null;
            /** @example 100.05 */
            price?: string | null;
            /** @example 0 */
            fee?: string | null;
            /** @example 0 */
            tax?: string | null;
            brokerOrderNo?: string | null;
            cashInLieuActionId: string | null;
            /** Format: date-time */
            tradeTime: string;
            note?: string | null;
            isDeleted: boolean;
            /** Format: date-time */
            deletedAt: string | null;
            account?: components["schemas"]["TransactionAccountSummaryDto"];
            asset?: components["schemas"]["TransactionAssetSummaryDto"] | null;
        };
        ImportTransactionsDto: {
            /**
             * @description Target brokerage account ID for the import
             * @example c2610e4e-1cca-401e-afa7-1ebf541d0000
             */
            accountId: string;
            /**
             * @description Raw CSV or TSV content copied from the uploaded brokerage file
             * @example 股名\t日期\t成交股數\t淨收付\t成交單價\t成交價金\t手續費\t交易稅\t稅款\t委託書號\t幣別\t備註
             */
            csvContent: string;
        };
        ImportTransactionsErrorDto: {
            /** @example 2 */
            row: number;
            /** @example 股名 */
            field: string;
            /** @example Asset alias not found for 富邦台50 */
            message: string;
        };
        ImportTransactionsResponseDto: {
            /** @example 3 */
            totalRows: number;
            /** @example 2 */
            successCount: number;
            /** @example 1 */
            failureCount: number;
            /**
             * @example [
             *       "9f5a51ae-1cca-401e-afa7-1ebf541d0000"
             *     ]
             */
            createdTransactionIds: string[];
            errors: components["schemas"]["ImportTransactionsErrorDto"][];
        };
        ImportResolvedAssetDto: {
            /** @example asset-id */
            id: string;
            /** @example 2330 */
            symbol: string;
            /** @example 台積電 */
            name: string;
        };
        ImportPreviewNormalizedTransactionDto: {
            /**
             * @example buy
             * @enum {string}
             */
            type: "buy" | "sell";
            /** @example 1000 */
            quantity: string;
            /** @example 1000 */
            unitPrice: string;
            /** @example TWD */
            currency: string;
            /** @example 20 */
            fees: string;
            /** @example 0 */
            taxes: string;
        };
        ImportRowIssueDto: {
            /**
             * @description Typed import issue code. Sell readiness codes: SELL_HISTORY_REQUIRED, SELL_INSUFFICIENT_LOTS, SELL_SAME_DAY_ORDER_AMBIGUOUS (row-local). DUPLICATE_BROKER_ORDER_IN_FILE is commit-blocking.
             * @example SELL_HISTORY_REQUIRED
             * @enum {string}
             */
            code: "INVALID_ROW" | "MISSING_REQUIRED_FIELD" | "DUPLICATE_BROKER_ORDER_IN_FILE" | "DUPLICATE_BROKER_ORDER_IN_ACCOUNT" | "DUPLICATE_BROKER_ORDER_ALREADY_IMPORTED" | "UNSUPPORTED_CURRENCY" | "CURRENCY_MISMATCH" | "ASSET_ALIAS_NOT_FOUND" | "SELL_HISTORY_REQUIRED" | "SELL_INSUFFICIENT_LOTS" | "SELL_SAME_DAY_ORDER_AMBIGUOUS" | "ACCOUNT_NOT_BROKER" | "UNSUPPORTED_BROKER" | "ACCOUNT_NOT_FOUND_OR_FORBIDDEN" | "COMMIT_NOT_ALLOWED_WITH_ERRORS" | "IMPORT_COMMIT_FAILED";
            /** @example quantity */
            field: string;
            /** @example Sell requires earlier buy history that is not available */
            message: string;
        };
        ImportPreviewRowDto: {
            /** @example 2 */
            row: number;
            /**
             * @example ready
             * @enum {string}
             */
            status: "ready" | "skipped" | "error" | "warning";
            /** @example 台積電 */
            rawAssetName: string;
            /** @example ABC123 */
            brokerOrderNo: string;
            /** @example 2026-07-01 */
            tradeDate: string;
            resolvedAsset: components["schemas"]["ImportResolvedAssetDto"] | null;
            normalizedTransaction: components["schemas"]["ImportPreviewNormalizedTransactionDto"] | null;
            errors: components["schemas"]["ImportRowIssueDto"][];
            warnings: components["schemas"]["ImportRowIssueDto"][];
        };
        ImportPreviewResponseDto: {
            /** @example 10 */
            totalRows: number;
            /** @example 8 */
            readyCount: number;
            /** @example 1 */
            skippedCount: number;
            /** @example 2 */
            errorCount: number;
            /** @example 0 */
            warningCount: number;
            /** @example false */
            canCommit: boolean;
            /**
             * @description Ready row numbers in chronological write order for commit
             * @example [
             *       3,
             *       2
             *     ]
             */
            writeOrderRowNumbers: number[];
            rows: components["schemas"]["ImportPreviewRowDto"][];
        };
        ImportCommitResponseDto: {
            /** @example 10 */
            totalRows: number;
            /** @example 10 */
            successCount: number;
            /** @example 0 */
            skippedCount: number;
            /** @example 0 */
            failureCount: number;
            /**
             * @example [
             *       "9f5a51ae-1cca-401e-afa7-1ebf541d0000"
             *     ]
             */
            createdTransactionIds: string[];
        };
        ImportCommitRejectedResponseDto: {
            /** @example 10 */
            totalRows: number;
            /** @example 0 */
            successCount: number;
            /** @example 0 */
            skippedCount: number;
            /** @example 2 */
            failureCount: number;
            /** @example COMMIT_NOT_ALLOWED_WITH_ERRORS */
            errorCode: string;
            /**
             * @example [
             *       "9f5a51ae-1cca-401e-afa7-1ebf541d0000"
             *     ]
             */
            createdTransactionIds: string[];
            preview: components["schemas"]["ImportPreviewResponseDto"];
        };
        TransactionListResponseDto: {
            total: number;
            skip: number;
            take: number;
            items: components["schemas"]["TransactionResponseDto"][];
        };
        CreateAndUpdateTransactionDto: {
            /**
             * @description 帳戶ID
             * @example c2610e4e-1cca-401e-afa7-1ebf541d0000
             */
            accountId?: string;
            /**
             * @description 資產ID
             * @example e8e1d0a6-1234-5678-9abc-def012345678
             */
            assetId?: string;
            /**
             * @description 交易類型
             * @example buy
             * @enum {string}
             */
            type?: "buy" | "sell" | "deposit" | "withdraw" | "dividend" | "fee";
            /**
             * @description 交易金額
             * @example 1000.5
             */
            amount?: number;
            /**
             * @description 交易數量
             * @example 10
             */
            quantity?: number;
            /**
             * @description 交易價格
             * @example 100.05
             */
            price?: number;
            /**
             * @description 手續費
             * @example 5
             */
            fee?: number;
            /**
             * @description 交易稅額
             * @example 3
             */
            tax?: number;
            /**
             * @description 券商委託書號
             * @example k0C1i
             */
            brokerOrderNo?: string;
            /**
             * @description 交易時間
             * @example 2025-01-20T10:30:00.000Z
             */
            tradeTime?: string;
            /**
             * @description 備註
             * @example Buy AAPL shares
             */
            note?: string;
        };
        MoneySummaryDto: {
            /** @example 1250 */
            amount: number;
            /** @example TWD */
            currency: string | null;
        };
        ReturnSummaryDto: {
            /** @example 1250 */
            amount: number;
            /** @example TWD */
            currency: string | null;
            /** @example 6.49 */
            rate: number;
        };
        InvestmentSummaryDto: {
            totalAssets: components["schemas"]["MoneySummaryDto"];
            totalReturn: components["schemas"]["ReturnSummaryDto"];
        };
        DashboardSummaryDto: {
            todayExpense: components["schemas"]["MoneySummaryDto"];
            monthExpense: components["schemas"]["MoneySummaryDto"];
            investment: components["schemas"]["InvestmentSummaryDto"];
        };
        DashboardAccountOverviewItemDto: {
            /** @example 3f3ccdc2-6bc0-4b4e-bf4b-f9936470d8eb */
            id: string;
            /** @example 資產-銀行(台幣) */
            name: string;
            /** @example bank */
            type: string;
            /** @example TWD */
            currency: string | null;
            /** @example 12850 */
            balance: number;
        };
        DashboardRecentActivityItemDto: {
            /** @example cashbook-5e9f57f5-9ca6-4ab6-b2ab-c28a3eb3894a */
            id: string;
            /**
             * @example cashbook
             * @enum {string}
             */
            kind: "cashbook" | "investment";
            /** @example 2026-03-18T09:00:00.000Z */
            date: string;
            /** @example Lunch */
            title: string;
            /** @example Expense · 資產-銀行(台幣) */
            subtitle: string;
            /** @example 180 */
            amount: number | null;
            /** @example TWD */
            currency: string | null;
            /**
             * @example out
             * @enum {string}
             */
            direction: "in" | "out" | "neutral";
        };
        DashboardActivityDto: {
            accountOverview: components["schemas"]["DashboardAccountOverviewItemDto"][];
            recentActivity: components["schemas"]["DashboardRecentActivityItemDto"][];
        };
        PortfolioSummaryResponseDto: {
            /**
             * @example preferred-base
             * @enum {string}
             */
            displayCurrencyMode: "portfolio-default" | "preferred-base";
            /** @example USD */
            requestedDisplayCurrency: string | null;
            /** @example USD */
            effectiveDisplayCurrency: string | null;
            /** @example 2026-04-05T00:00:00.000Z */
            asOf: string;
            /** @example TWD */
            baseCurrency: string | null;
            /** @example 125000 */
            investedCapital: number;
            /** @example 138600 */
            marketValue: number;
            /** @example 13600 */
            totalPnl: number;
            /** @example 0.1088 */
            totalReturnRate: number;
            /** @example 4 */
            holdingsCount: number;
        };
        PortfolioHoldingLastActivityDto: {
            /**
             * @example buy
             * @enum {string}
             */
            type: "buy" | "sell" | "deposit" | "withdraw" | "dividend" | "fee";
            /**
             * @description UTC 日期 YYYY-MM-DD
             * @example 2026-04-04
             */
            tradeDate: string;
            /** @description 使用者自己寫的備註。沒有備註時前端用 type 與 tradeDate 組文案。 */
            note: string | null;
        };
        PortfolioHoldingItemResponseDto: {
            /** @example asset-1 */
            assetId: string;
            /** @example AAPL */
            symbol: string;
            /** @example Apple Inc. */
            name: string;
            /**
             * @example equity
             * @enum {string}
             */
            type: "equity" | "etf" | "crypto" | "cash";
            /**
             * @example equity
             * @enum {string}
             */
            assetClass: "equity" | "bond" | "cash" | "crypto" | "precious_metal";
            /** @example 12.5 */
            quantity: number;
            /** @example 102.35 */
            avgCost: number;
            /** @example 118.2 */
            latestPrice: number | null;
            /** @example USD */
            latestPriceCurrency: string | null;
            /** @example USD */
            assetBaseCurrency: string;
            /** @example 1279.375 */
            investedAmount: number;
            /** @example 1477.5 */
            marketValue: number;
            /** @example 198.125 */
            pnl: number;
            /** @example 0.154859472 */
            returnRate: number;
            /** @example 0.2764 */
            weight: number;
            /** @description 最近一筆交易的種類與日期。文案由前端 i18n 組，不回英文句子（PR #46）。 */
            lastActivity: components["schemas"]["PortfolioHoldingLastActivityDto"] | null;
        };
        PortfolioAllocationByTypeItemResponseDto: {
            /**
             * @example equity
             * @enum {string}
             */
            type: "equity" | "etf" | "crypto" | "cash";
            /** @example 48600 */
            marketValue: number;
            /** @example 0.35 */
            weight: number;
        };
        PortfolioAllocationByAssetClassItemResponseDto: {
            /**
             * @example equity
             * @enum {string}
             */
            assetClass: "equity" | "bond" | "cash" | "crypto" | "precious_metal";
            /** @example 48600 */
            marketValue: number;
            /** @example 0.35 */
            weight: number;
        };
        PortfolioHoldingsResponseDto: {
            /**
             * @example preferred-base
             * @enum {string}
             */
            displayCurrencyMode: "portfolio-default" | "preferred-base";
            /** @example USD */
            requestedDisplayCurrency: string | null;
            /** @example USD */
            effectiveDisplayCurrency: string | null;
            items: components["schemas"]["PortfolioHoldingItemResponseDto"][];
            allocationByType: components["schemas"]["PortfolioAllocationByTypeItemResponseDto"][];
            allocationByAssetClass: components["schemas"]["PortfolioAllocationByAssetClassItemResponseDto"][];
        };
        PortfolioRebalanceAllocationResponseDto: {
            /** @example 0.8 */
            equity: number;
            /** @example 0.2 */
            bond: number;
        };
        PortfolioRebalanceMarketValueResponseDto: {
            /** @example 80000 */
            equity: number;
            /** @example 20000 */
            bond: number;
        };
        PortfolioRebalanceCandidateResponseDto: {
            /**
             * @example equity
             * @enum {string}
             */
            assetClass: "equity" | "bond";
            /** @example asset-1 */
            assetId: string;
            /** @example AAPL */
            symbol: string;
            /** @example Apple Inc. */
            name: string;
            /** @example 2480.67063 */
            currentMarketValue: number;
            /** @example 1 */
            currentWeightWithinAssetClass: number;
            /** @example 250 */
            latestPrice: number | null;
            /** @example USD */
            latestPriceCurrency: string | null;
            /** @example USD */
            assetBaseCurrency: string;
            /** @example null */
            lotSize: number | null;
            /** @example null */
            minTradeUnit: number | null;
        };
        PortfolioRebalanceSuggestionResponseDto: {
            /**
             * @example equity
             * @enum {string}
             */
            assetClass: "equity" | "bond";
            /** @example asset-1 */
            assetId: string;
            /** @example AAPL */
            symbol: string;
            /** @example Apple Inc. */
            name: string;
            /** @example 2480.67063 */
            currentMarketValue: number;
            /** @example 1 */
            currentWeightWithinAssetClass: number;
            /** @example 9689.32937 */
            suggestedBuyAmount: number;
            /** @example 38.75731748 */
            estimatedQuantity: number | null;
            /** @example 250 */
            latestPrice: number | null;
            /** @example USD */
            latestPriceCurrency: string | null;
        };
        PortfolioRebalanceResponseDto: {
            /**
             * @example preferred-base
             * @enum {string}
             */
            displayCurrencyMode: "portfolio-default" | "preferred-base";
            /** @example USD */
            requestedDisplayCurrency: string | null;
            /** @example USD */
            effectiveDisplayCurrency: string | null;
            /** @example 2026-04-19T00:00:00.000Z */
            asOf: string;
            /** @example USD */
            baseCurrency: string | null;
            targets: components["schemas"]["PortfolioRebalanceAllocationResponseDto"];
            current: components["schemas"]["PortfolioRebalanceAllocationResponseDto"];
            gaps: components["schemas"]["PortfolioRebalanceAllocationResponseDto"];
            marketValueByAssetClass: components["schemas"]["PortfolioRebalanceMarketValueResponseDto"];
            recommendedBuyAmountByAssetClass: components["schemas"]["PortfolioRebalanceMarketValueResponseDto"];
            /** @example 100000 */
            trackedMarketValue: number;
            candidates: components["schemas"]["PortfolioRebalanceCandidateResponseDto"][];
            suggestions: components["schemas"]["PortfolioRebalanceSuggestionResponseDto"][];
            /**
             * @example [
             *       "Current ratios are calculated from equity and bond holdings only."
             *     ]
             */
            notes: string[];
        };
        PortfolioTrendPointResponseDto: {
            /** @example 2026-04-05 */
            label: string;
            /** @example 2026-04-05 */
            date: string;
            /** @example 125000 */
            investedCapital: number;
            /** @example 138600 */
            marketValue: number;
        };
        PortfolioTrendResponseDto: {
            /**
             * @example preferred-base
             * @enum {string}
             */
            displayCurrencyMode: "portfolio-default" | "preferred-base";
            /** @example USD */
            requestedDisplayCurrency: string | null;
            /** @example USD */
            effectiveDisplayCurrency: string | null;
            points: components["schemas"]["PortfolioTrendPointResponseDto"][];
        };
        PortfolioHoldingTrendPointResponseDto: {
            /** @example 2026-04-05 */
            label: string;
            /** @example 2026-04-05 */
            date: string;
            /** @example 4200 */
            investedAmount: number;
            /** @example 4500 */
            marketValue: number;
        };
        PortfolioHoldingTrendResponseDto: {
            /**
             * @example preferred-base
             * @enum {string}
             */
            displayCurrencyMode: "portfolio-default" | "preferred-base";
            /** @example USD */
            requestedDisplayCurrency: string | null;
            /** @example USD */
            effectiveDisplayCurrency: string | null;
            /** @example asset-1 */
            assetId: string;
            points: components["schemas"]["PortfolioHoldingTrendPointResponseDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    HealthController_ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liveness probe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AssetsController_findAll: {
        parameters: {
            query?: {
                /** @description Keyword search over symbol and name */
                q?: string;
                /** @description Asset type filter */
                type?: "equity" | "etf" | "crypto" | "cash";
                /** @description Asset class filter */
                assetClass?: "equity" | "bond" | "cash" | "crypto" | "precious_metal";
                /** @description Base currency filter */
                baseCurrency?: "TWD" | "USD" | "JPY" | "EUR";
                page?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AssetsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAndUpdateAssetDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AssetsController_createAlias: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetAliasDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetAliasResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetAliasConflictResponseDto"];
                };
            };
        };
    };
    AssetsController_findBySymbol: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AssetsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AssetsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AssetsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAndUpdateAssetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    FxRateController_getTodayRate: {
        parameters: {
            query?: {
                /** @description Base currency for the requested FX reference rate */
                base?: "TWD" | "USD";
                /** @description Quote currency for the requested FX reference rate */
                quote?: "TWD" | "USD";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxRateResponseDto"];
                };
            };
        };
    };
    MarketPriceController_refreshPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshPricesResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    MarketPriceController_syncTaiwanPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncTaiwanPricesDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncTaiwanPricesResponseDto"];
                };
            };
        };
    };
    MarketPriceController_syncUsPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncUsPricesDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncUsPricesResponseDto"];
                };
            };
        };
    };
    CorpActionController_syncSplits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncSplitsDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncSplitsResponseDto"];
                };
            };
        };
    };
    CashInLieuController_record: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashInLieuDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GlController_getAccounts: {
        parameters: {
            query: {
                type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAccountDto"][];
                };
            };
        };
    };
    GlController_getEntries: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlEntryDto"][];
                };
            };
        };
    };
    GlController_transfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostTransferCommand"];
            };
        };
        responses: {
            /** @description Created GL entry with two lines */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GlController_expense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostExpenseCommand"];
            };
        };
        responses: {
            /** @description Created GL entry for an expense (debit expense, credit cash/bank). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed or not balanced. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GlController_income: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostIncomeCommand"];
            };
        };
        responses: {
            /** @description Created GL entry for an income (debit cash/bank, credit income). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed or not balanced. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AccountsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponseDto"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AccountsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAndUpdateAccountDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AccountsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AccountsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AccountsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAndUpdateAccountDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    OnboardingController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingSignupDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingSignupResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TransactionsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TransactionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TransactionsController_importTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportTransactionsDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportTransactionsResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TransactionsController_previewImportTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportTransactionsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreviewResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TransactionsController_commitImportTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportTransactionsDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportCommitResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportCommitRejectedResponseDto"];
                };
            };
        };
    };
    TransactionsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TransactionsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TransactionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAndUpdateTransactionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TransactionsController_hardDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DashboardController_getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryDto"];
                };
            };
        };
    };
    DashboardController_getActivity: {
        parameters: {
            query?: {
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardActivityDto"];
                };
            };
        };
    };
    PortfolioController_getSummary: {
        parameters: {
            query?: {
                /** @description Deprecated alias for preferredBaseCurrency */
                displayCurrency?: "TWD" | "USD" | "JPY" | "EUR";
                /** @description Preferred display currency for normalized portfolio values */
                preferredBaseCurrency?: "TWD" | "USD" | "JPY" | "EUR";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummaryResponseDto"];
                };
            };
        };
    };
    PortfolioController_getHoldings: {
        parameters: {
            query?: {
                /** @description Deprecated alias for preferredBaseCurrency */
                displayCurrency?: "TWD" | "USD" | "JPY" | "EUR";
                /** @description Preferred display currency for normalized portfolio values */
                preferredBaseCurrency?: "TWD" | "USD" | "JPY" | "EUR";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioHoldingsResponseDto"];
                };
            };
        };
    };
    PortfolioController_getRebalance: {
        parameters: {
            query?: {
                /** @description Deprecated alias for preferredBaseCurrency */
                displayCurrency?: "TWD" | "USD" | "JPY" | "EUR";
                /** @description Preferred display currency for normalized portfolio values */
                preferredBaseCurrency?: "TWD" | "USD" | "JPY" | "EUR";
                /** @description Target equity allocation ratio. If omitted, backend uses the default or derives it from targetBond. */
                targetEquity?: number;
                /** @description Target bond allocation ratio. If omitted, backend uses the default or derives it from targetEquity. */
                targetBond?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioRebalanceResponseDto"];
                };
            };
        };
    };
    PortfolioController_getTrend: {
        parameters: {
            query?: {
                /** @description Deprecated alias for preferredBaseCurrency */
                displayCurrency?: "TWD" | "USD" | "JPY" | "EUR";
                /** @description Preferred display currency for normalized portfolio values */
                preferredBaseCurrency?: "TWD" | "USD" | "JPY" | "EUR";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioTrendResponseDto"];
                };
            };
        };
    };
    PortfolioController_getHoldingTrend: {
        parameters: {
            query?: {
                /** @description Deprecated alias for preferredBaseCurrency */
                displayCurrency?: "TWD" | "USD" | "JPY" | "EUR";
                /** @description Preferred display currency for normalized portfolio values */
                preferredBaseCurrency?: "TWD" | "USD" | "JPY" | "EUR";
            };
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioHoldingTrendResponseDto"];
                };
            };
        };
    };
}
